using FFP.Purchasing.Tablet.Models; using FFP.Purchasing.Tablet.Services;
namespace FFP.Purchasing.Tablet.Pages;
public sealed class RequestEditorPage:ContentPage {
 private readonly PurchaseRequest _r;private readonly IPurchaseStore _store;private readonly ILocalItemCache _items;private readonly IAttachmentService _attachments;private readonly ISyncService _sync;private readonly IRequestValidator _validator;private readonly IAuditService _audit;
 private readonly VerticalStackLayout _lines=new(){Spacing=8};private readonly VerticalStackLayout _docs=new(){Spacing=8};private readonly Label _total=new(){FontSize=20,FontAttributes=FontAttributes.Bold};
 public RequestEditorPage(PurchaseRequest r,IPurchaseStore store,ILocalItemCache items,IAttachmentService attachments,ISyncService sync,IRequestValidator validator,IAuditService audit){_r=r;_store=store;_items=items;_attachments=attachments;_sync=sync;_validator=validator;_audit=audit;Title=r.LocalNumber;
 var add=new Button{Text="Add Item"};add.Clicked+=AddItem;var photo=new Button{Text="Take Photo"};photo.Clicked+=Photo;var file=new Button{Text="Choose Files"};file.Clicked+=Files;var submit=new Button{Text="Submit Request",BackgroundColor=Color.FromArgb("#0B4F8A"),TextColor=Colors.White};submit.Clicked+=Submit;
 Content=new ScrollView{Content=new VerticalStackLayout{Padding=24,Spacing=12,Children={new Label{Text=$"{r.Type} • {r.VendorName??"No vendor"}",FontSize=24,FontAttributes=FontAttributes.Bold},new Label{Text=r.Purpose},new Label{Text="Items",FontAttributes=FontAttributes.Bold},new Label{Text="Items are learned locally from entries on this tablet. No FFP Manager item catalog is used.",FontSize=12},_lines,add,_total,new Label{Text="Supporting Documents",FontAttributes=FontAttributes.Bold},new HorizontalStackLayout{Children={photo,file}},_docs,submit}}};Render();}
 private async void AddItem(object?s,EventArgs e){var learned=await _items.SearchAsync();var hint=learned.FirstOrDefault();var description=await DisplayPromptAsync("Item","Enter item description",initialValue:hint?.Description);if(string.IsNullOrWhiteSpace(description))return;var match=(await _items.SearchAsync(description)).FirstOrDefault(x=>x.Description.Equals(description,StringComparison.OrdinalIgnoreCase));var uom=await DisplayPromptAsync("UOM","Unit of measure",initialValue:match?.LastUom??"EA");if(string.IsNullOrWhiteSpace(uom))return;var qtyText=await DisplayPromptAsync("Quantity","Quantity",initialValue:"1",keyboard:Keyboard.Numeric);var priceText=await DisplayPromptAsync("Unit Price","Enter current unit price",initialValue:"",keyboard:Keyboard.Numeric);decimal.TryParse(qtyText,out var qty);decimal.TryParse(priceText,out var price);_r.Lines.Add(new PurchaseLine{Description=description.Trim(),Uom=uom.Trim().ToUpperInvariant(),Quantity=qty<=0?1:qty,UnitPrice=price});await _items.LearnAsync(description,uom,price);await _store.SaveAsync(_r);await _audit.WriteAsync("LineAdded",_r.Id,description);Render();}
 private async void Photo(object?s,EventArgs e){var a=await _attachments.CapturePhotoAsync();if(a!=null){_r.Attachments.Add(a);await _store.SaveAsync(_r);await _audit.WriteAsync("AttachmentAdded",_r.Id,a.FileName);Render();}}
 private async void Files(object?s,EventArgs e){var files=await _attachments.PickFilesAsync();_r.Attachments.AddRange(files);await _store.SaveAsync(_r);foreach(var a in files)await _audit.WriteAsync("AttachmentAdded",_r.Id,a.FileName);Render();}
 private async void Submit(object?s,EventArgs e){var issues=_validator.Validate(_r);if(issues.Count>0){await DisplayAlert("Cannot submit",string.Join(Environment.NewLine,issues.Select(x=>$"{x.Field}: {x.Message}")),"OK");return;}await _audit.WriteAsync("SubmitStarted",_r.Id);var result=await _sync.SubmitAsync(_r);await _audit.WriteAsync(result.Succeeded?"SubmitSucceeded":"SubmitPending",_r.Id,result.Message);await DisplayAlert(result.Succeeded?"Submitted":"Pending",result.Message,"OK");Render();}
 private void Render(){_lines.Children.Clear();foreach(var l in _r.Lines)_lines.Children.Add(new Label{Text=$"{l.Quantity:0.##} {l.Uom}  {l.Description}  @ {l.UnitPrice:C} = {l.Total:C}"});_docs.Children.Clear();foreach(var a in _r.Attachments)_docs.Children.Add(new Label{Text=$"{a.FileName} • {(a.PendingSync?"Pending Sync":"Synced")}"});_total.Text=$"Total: {_r.Total:C} • {_r.Status}";}
}